name: what_we_eat
description: A Flutter application to decide what to eat.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#0078d4"               
  android_12:
    icon_background_color: "#0078d4"