name: what_we_eat
description: A Flutter application to decide what to eat.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  english_words: ^4.0.0
  provider: ^6.0.0
  url_launcher: ^6.1.0
  sqflite: ^2.3.0    #SQLite 依赖
  path: ^1.8.3       #路径拼接依赖
  path_provider: ^2.1.1   #获取数据库存储路径
  shared_preferences: ^2.5.4
  device_info_plus: ^12.3.0
  uuid: ^4.5.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/transparent_icon.png
    - assets/data/foods.json
    - assets/data/raw_material.json
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0078d4"
  background_color: "#0078D4"


flutter_native_splash:
  color: "#0078d4"
  image: assets/images/transparent_icon.png               
  android_12:
    icon_background_color: "#0078d4"
    image: assets/images/transparent_icon.png